DROP DATABASE IF EXISTS "1984";

CREATE DATABASE "1984"
    WITH
    TEMPLATE = template0
    ENCODING = 'UTF8'
    LOCALE_PROVIDER = libc
    LOCALE = 'Russian_Russia.1251';

\connect "1984"

SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;

DROP TABLE IF EXISTS public.reports CASCADE;
DROP TABLE IF EXISTS public.violations CASCADE;
DROP TABLE IF EXISTS public.screenshots CASCADE;
DROP TABLE IF EXISTS public.web_activity CASCADE;
DROP TABLE IF EXISTS public.dns_cache_records CASCADE;
DROP TABLE IF EXISTS public.window_activity CASCADE;
DROP TABLE IF EXISTS public.activity_periods CASCADE;
DROP TABLE IF EXISTS public.activity_events CASCADE;
DROP TABLE IF EXISTS public.application_rules CASCADE;
DROP TABLE IF EXISTS public.web_resource_rules CASCADE;
DROP TABLE IF EXISTS public.workstations CASCADE;
DROP TABLE IF EXISTS public.activity_period_types CASCADE;
DROP TABLE IF EXISTS public.rule_types CASCADE;

CREATE TABLE public.workstations (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ip_address character varying(45) NOT NULL,
    username character varying(255) NOT NULL,
    domain_name character varying(255),
    host_name character varying(255) NOT NULL,
    CONSTRAINT unique_workstation_ip UNIQUE (ip_address)
);

CREATE TABLE public.activity_events (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workstation_id integer NOT NULL,
    last_active_time timestamp without time zone NOT NULL,
    CONSTRAINT unique_activity_workstation UNIQUE (workstation_id),
    CONSTRAINT activity_events_workstation_id_fkey
        FOREIGN KEY (workstation_id)
        REFERENCES public.workstations(id)
        ON DELETE CASCADE
);

CREATE TABLE public.activity_period_types (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(20) NOT NULL,
    CONSTRAINT activity_period_types_name_key UNIQUE (name)
);

CREATE TABLE public.activity_periods (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workstation_id integer NOT NULL,
    start_time timestamp without time zone NOT NULL,
    end_time timestamp without time zone,
    duration_seconds integer,
    period_type_id integer NOT NULL,
    CONSTRAINT activity_periods_workstation_id_fkey
        FOREIGN KEY (workstation_id)
        REFERENCES public.workstations(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_activity_period_type
        FOREIGN KEY (period_type_id)
        REFERENCES public.activity_period_types(id)
);

CREATE TABLE public.window_activity (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workstation_id integer NOT NULL,
    window_title text NOT NULL,
    process_name character varying(255) NOT NULL,
    process_id integer,
    start_time timestamp without time zone NOT NULL,
    end_time timestamp without time zone,
    duration_seconds integer,
    CONSTRAINT window_activity_workstation_id_fkey
        FOREIGN KEY (workstation_id)
        REFERENCES public.workstations(id)
        ON DELETE CASCADE
);

CREATE TABLE public.web_activity (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workstation_id integer NOT NULL,
    process_name character varying(255),
    window_title text,
    domain_name character varying(255) NOT NULL,
    detection_method character varying(50) NOT NULL,
    access_time timestamp without time zone NOT NULL,
    CONSTRAINT web_activity_detection_method_check
        CHECK (detection_method IN ('window_title', 'dns_cache', 'combined')),
    CONSTRAINT web_activity_workstation_id_fkey
        FOREIGN KEY (workstation_id)
        REFERENCES public.workstations(id)
        ON DELETE CASCADE
);

CREATE TABLE public.dns_cache_records (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workstation_id integer NOT NULL,
    domain_name character varying(255) NOT NULL,
    resolved_ip character varying(45),
    record_time timestamp without time zone NOT NULL,
    CONSTRAINT dns_cache_records_workstation_id_fkey
        FOREIGN KEY (workstation_id)
        REFERENCES public.workstations(id)
        ON DELETE CASCADE
);

CREATE TABLE public.screenshots (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workstation_id integer NOT NULL,
    file_path text NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT screenshots_workstation_id_fkey
        FOREIGN KEY (workstation_id)
        REFERENCES public.workstations(id)
        ON DELETE CASCADE
);

CREATE TABLE public.rule_types (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(20) NOT NULL,
    CONSTRAINT rule_types_name_key UNIQUE (name)
);

CREATE TABLE public.application_rules (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_name character varying(255) NOT NULL,
    rule_type_id integer NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT application_rules_rule_type_id_fkey
        FOREIGN KEY (rule_type_id)
        REFERENCES public.rule_types(id)
);

CREATE TABLE public.web_resource_rules (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    domain_name character varying(255) NOT NULL,
    rule_type_id integer NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT web_resource_rules_rule_type_id_fkey
        FOREIGN KEY (rule_type_id)
        REFERENCES public.rule_types(id)
);

CREATE TABLE public.violations (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workstation_id integer NOT NULL,
    source_table character varying(50),
    source_event_id integer,
    violation_type character varying(50) NOT NULL,
    severity character varying(20) DEFAULT 'medium' NOT NULL,
    description text NOT NULL,
    related_entity text,
    rule_source character varying(100),
    detected_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_resolved boolean DEFAULT false NOT NULL,
    resolved_at timestamp without time zone,
    resolution_comment text,
    CONSTRAINT violations_severity_check
        CHECK (severity IN ('low', 'medium', 'high', 'critical')),
    CONSTRAINT violations_violation_type_check
        CHECK (violation_type IN ('blacklist_application', 'blacklist_web_resource', 'long_idle')),
    CONSTRAINT violations_workstation_id_fkey
        FOREIGN KEY (workstation_id)
        REFERENCES public.workstations(id)
        ON DELETE CASCADE
);

CREATE TABLE public.reports (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workstation_id integer NOT NULL,
    period_start date NOT NULL,
    period_end date NOT NULL,
    report_type character varying(50) DEFAULT 'daily_activity_report' NOT NULL,
    report_data jsonb NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT reports_workstation_id_fkey
        FOREIGN KEY (workstation_id)
        REFERENCES public.workstations(id)
        ON DELETE CASCADE
);

INSERT INTO public.activity_period_types (name)
VALUES
    ('active'),
    ('idle')
ON CONFLICT (name) DO NOTHING;

INSERT INTO public.rule_types (name)
VALUES
    ('whitelist'),
    ('blacklist')
ON CONFLICT (name) DO NOTHING;